version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONT_PORT:-3000}:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "${BACK_PORT:-4000}:4000"
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  db_data:
  portainer_data:
